# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .addressable_all_of import AddressableAllOf
from .extensible import Extensible


class Addressable(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Addressable - a model defined in OpenAPI

        type: The type of this Addressable.
        base_type: The base_type of this Addressable [Optional].
        schema_location: The schema_location of this Addressable [Optional].
        id: The id of this Addressable.
        href: The href of this Addressable [Optional].
        name: The name of this Addressable [Optional].
    """

    type: str
    base_type: Optional[str] = None
    schema_location: Optional[AnyUrl] = None
    id: str
    href: Optional[AnyUrl] = None
    name: Optional[str] = None

Addressable.update_forward_refs()
