# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class AttachmentRefAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AttachmentRefAllOf - a model defined in OpenAPI

        description: The description of this AttachmentRefAllOf [Optional].
        url: The url of this AttachmentRefAllOf [Optional].
    """

    description: Optional[str] = None
    url: Optional[AnyUrl] = None

AttachmentRefAllOf.update_forward_refs()
