# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .addressable import Addressable
from .note import Note
from .related_party_ref import RelatedPartyRef
from .service_order_create_all_of import ServiceOrderCreateAllOf
from .service_order_item import ServiceOrderItem
from .service_order_relationship import ServiceOrderRelationship


class ServiceOrderCreate(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceOrderCreate - a model defined in OpenAPI

        type: The type of this ServiceOrderCreate.
        base_type: The base_type of this ServiceOrderCreate [Optional].
        schema_location: The schema_location of this ServiceOrderCreate [Optional].
        id: The id of this ServiceOrderCreate.
        href: The href of this ServiceOrderCreate [Optional].
        name: The name of this ServiceOrderCreate [Optional].
        external_id: The external_id of this ServiceOrderCreate [Optional].
        description: The description of this ServiceOrderCreate [Optional].
        category: The category of this ServiceOrderCreate [Optional].
        note: The note of this ServiceOrderCreate [Optional].
        notification_contact: The notification_contact of this ServiceOrderCreate [Optional].
        priority: The priority of this ServiceOrderCreate [Optional].
        requested_start_date: The requested_start_date of this ServiceOrderCreate [Optional].
        requested_completion_date: The requested_completion_date of this ServiceOrderCreate [Optional].
        related_party: The related_party of this ServiceOrderCreate [Optional].
        order_item: The order_item of this ServiceOrderCreate [Optional].
        order_relationship: The order_relationship of this ServiceOrderCreate [Optional].
    """

    type: str
    base_type: Optional[str] = None
    schema_location: Optional[AnyUrl] = None
    id: str
    href: Optional[AnyUrl] = None
    name: Optional[str] = None
    external_id: Optional[str] = None
    description: Optional[str] = None
    category: Optional[str] = None
    note: Optional[List[Note]] = None
    notification_contact: Optional[str] = None
    priority: Optional[int] = None
    requested_start_date: Optional[datetime] = None
    requested_completion_date: Optional[datetime] = None
    related_party: Optional[List[RelatedPartyRef]] = None
    order_item: Optional[List[ServiceOrderItem]] = None
    order_relationship: Optional[List[ServiceOrderRelationship]] = None

ServiceOrderCreate.update_forward_refs()
