# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .service_order_ref import ServiceOrderRef


class ServiceAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceAllOf - a model defined in OpenAPI

        end_date: The end_date of this ServiceAllOf [Optional].
        has_started: The has_started of this ServiceAllOf [Optional].
        is_service_enabled: The is_service_enabled of this ServiceAllOf [Optional].
        is_stateful: The is_stateful of this ServiceAllOf [Optional].
        service_date: The service_date of this ServiceAllOf [Optional].
        service_order: The service_order of this ServiceAllOf [Optional].
        start_date: The start_date of this ServiceAllOf [Optional].
        start_mode: The start_mode of this ServiceAllOf [Optional].
    """

    end_date: Optional[datetime] = None
    has_started: Optional[bool] = None
    is_service_enabled: Optional[bool] = None
    is_stateful: Optional[bool] = None
    service_date: Optional[str] = None
    service_order: Optional[List[ServiceOrderRef]] = None
    start_date: Optional[datetime] = None
    start_mode: Optional[str] = None

ServiceAllOf.update_forward_refs()
