# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .service_specification_relationship_type import ServiceSpecificationRelationshipType
from .time_period import TimePeriod


class ServiceSpecificationRelationshipAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceSpecificationRelationshipAllOf - a model defined in OpenAPI

        relationship_type: The relationship_type of this ServiceSpecificationRelationshipAllOf [Optional].
        role: The role of this ServiceSpecificationRelationshipAllOf [Optional].
        valid_for: The valid_for of this ServiceSpecificationRelationshipAllOf [Optional].
    """

    relationship_type: Optional[ServiceSpecificationRelationshipType] = None
    role: Optional[str] = None
    valid_for: Optional[TimePeriod] = None

ServiceSpecificationRelationshipAllOf.update_forward_refs()
