# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .order_relationship_type import OrderRelationshipType
from .service_order_ref import ServiceOrderRef


class ServiceOrderRelationship(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceOrderRelationship - a model defined in OpenAPI

        relationship_type: The relationship_type of this ServiceOrderRelationship.
        service_order: The service_order of this ServiceOrderRelationship.
    """

    relationship_type: OrderRelationshipType
    service_order: ServiceOrderRef

ServiceOrderRelationship.update_forward_refs()
