# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .service_order_state_type import ServiceOrderStateType


class ServiceOrderAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceOrderAllOf - a model defined in OpenAPI

        state: The state of this ServiceOrderAllOf [Optional].
        order_date: The order_date of this ServiceOrderAllOf [Optional].
        start_date: The start_date of this ServiceOrderAllOf [Optional].
        expected_completion_date: The expected_completion_date of this ServiceOrderAllOf [Optional].
        completion_date: The completion_date of this ServiceOrderAllOf [Optional].
    """

    state: Optional[ServiceOrderStateType] = None
    order_date: Optional[datetime] = None
    start_date: Optional[datetime] = None
    expected_completion_date: Optional[datetime] = None
    completion_date: Optional[datetime] = None

ServiceOrderAllOf.update_forward_refs()
