# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .addressable import Addressable
from .service_spec_characteristic_all_of import ServiceSpecCharacteristicAllOf
from .service_spec_characteristic_value import ServiceSpecCharacteristicValue
from .service_specification_relationship import ServiceSpecificationRelationship
from .time_period import TimePeriod


class ServiceSpecCharacteristic(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceSpecCharacteristic - a model defined in OpenAPI

        type: The type of this ServiceSpecCharacteristic.
        base_type: The base_type of this ServiceSpecCharacteristic [Optional].
        schema_location: The schema_location of this ServiceSpecCharacteristic [Optional].
        id: The id of this ServiceSpecCharacteristic.
        href: The href of this ServiceSpecCharacteristic [Optional].
        name: The name of this ServiceSpecCharacteristic [Optional].
        value_schema_location: The value_schema_location of this ServiceSpecCharacteristic [Optional].
        value_type: The value_type of this ServiceSpecCharacteristic [Optional].
        description: The description of this ServiceSpecCharacteristic [Optional].
        extensible: The extensible of this ServiceSpecCharacteristic [Optional].
        is_unique: The is_unique of this ServiceSpecCharacteristic [Optional].
        max_cardinality: The max_cardinality of this ServiceSpecCharacteristic [Optional].
        min_cardinality: The min_cardinality of this ServiceSpecCharacteristic [Optional].
        regex: The regex of this ServiceSpecCharacteristic [Optional].
        valid_for: The valid_for of this ServiceSpecCharacteristic [Optional].
        service_spec_char_relationship: The service_spec_char_relationship of this ServiceSpecCharacteristic [Optional].
        service_spec_characteristic_value: The service_spec_characteristic_value of this ServiceSpecCharacteristic [Optional].
    """

    type: str
    base_type: Optional[str] = None
    schema_location: Optional[AnyUrl] = None
    id: str
    href: Optional[AnyUrl] = None
    name: Optional[str] = None
    value_schema_location: Optional[str] = None
    value_type: Optional[str] = None
    description: Optional[str] = None
    extensible: Optional[bool] = None
    is_unique: Optional[bool] = None
    max_cardinality: Optional[int] = None
    min_cardinality: Optional[int] = None
    regex: Optional[str] = None
    valid_for: Optional[TimePeriod] = None
    service_spec_char_relationship: Optional[List[ServiceSpecificationRelationship]] = None
    service_spec_characteristic_value: Optional[List[ServiceSpecCharacteristicValue]] = None

ServiceSpecCharacteristic.update_forward_refs()
