# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .note import Note
from .related_party_ref import RelatedPartyRef
from .service_order_item import ServiceOrderItem
from .service_order_relationship import ServiceOrderRelationship


class ServiceOrderCreateAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceOrderCreateAllOf - a model defined in OpenAPI

        external_id: The external_id of this ServiceOrderCreateAllOf [Optional].
        description: The description of this ServiceOrderCreateAllOf [Optional].
        category: The category of this ServiceOrderCreateAllOf [Optional].
        note: The note of this ServiceOrderCreateAllOf [Optional].
        notification_contact: The notification_contact of this ServiceOrderCreateAllOf [Optional].
        priority: The priority of this ServiceOrderCreateAllOf [Optional].
        requested_start_date: The requested_start_date of this ServiceOrderCreateAllOf [Optional].
        requested_completion_date: The requested_completion_date of this ServiceOrderCreateAllOf [Optional].
        related_party: The related_party of this ServiceOrderCreateAllOf [Optional].
        order_item: The order_item of this ServiceOrderCreateAllOf [Optional].
        order_relationship: The order_relationship of this ServiceOrderCreateAllOf [Optional].
    """

    external_id: Optional[str] = None
    description: Optional[str] = None
    category: Optional[str] = None
    note: Optional[List[Note]] = None
    notification_contact: Optional[str] = None
    priority: Optional[int] = None
    requested_start_date: Optional[datetime] = None
    requested_completion_date: Optional[datetime] = None
    related_party: Optional[List[RelatedPartyRef]] = None
    order_item: Optional[List[ServiceOrderItem]] = None
    order_relationship: Optional[List[ServiceOrderRelationship]] = None

ServiceOrderCreateAllOf.update_forward_refs()
