# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .attachment_ref import AttachmentRef
from .related_party_ref import RelatedPartyRef
from .service_level_specification_ref import ServiceLevelSpecificationRef
from .service_spec_characteristic import ServiceSpecCharacteristic
from .service_specification_relationship import ServiceSpecificationRelationship
from .service_specification_state import ServiceSpecificationState
from .target_service_schema import TargetServiceSchema
from .time_period import TimePeriod


class ServiceSpecificationAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceSpecificationAllOf - a model defined in OpenAPI

        category: The category of this ServiceSpecificationAllOf [Optional].
        subcategory: The subcategory of this ServiceSpecificationAllOf [Optional].
        version: The version of this ServiceSpecificationAllOf [Optional].
        description: The description of this ServiceSpecificationAllOf [Optional].
        is_bundle: The is_bundle of this ServiceSpecificationAllOf [Optional].
        last_update: The last_update of this ServiceSpecificationAllOf [Optional].
        valid_for: The valid_for of this ServiceSpecificationAllOf [Optional].
        lifecycle_status: The lifecycle_status of this ServiceSpecificationAllOf [Optional].
        attachment: The attachment of this ServiceSpecificationAllOf [Optional].
        related_party: The related_party of this ServiceSpecificationAllOf [Optional].
        service_level_specification: The service_level_specification of this ServiceSpecificationAllOf [Optional].
        service_spec_relationship: The service_spec_relationship of this ServiceSpecificationAllOf [Optional].
        service_spec_characteristic: The service_spec_characteristic of this ServiceSpecificationAllOf [Optional].
        target_service_schema: The target_service_schema of this ServiceSpecificationAllOf [Optional].
    """

    category: Optional[str] = None
    subcategory: Optional[str] = None
    version: Optional[str] = None
    description: Optional[str] = None
    is_bundle: Optional[bool] = None
    last_update: Optional[datetime] = None
    valid_for: Optional[TimePeriod] = None
    lifecycle_status: Optional[ServiceSpecificationState] = None
    attachment: Optional[List[AttachmentRef]] = None
    related_party: Optional[List[RelatedPartyRef]] = None
    service_level_specification: Optional[List[ServiceLevelSpecificationRef]] = None
    service_spec_relationship: Optional[List[ServiceSpecificationRelationship]] = None
    service_spec_characteristic: Optional[List[ServiceSpecCharacteristic]] = None
    target_service_schema: Optional[TargetServiceSchema] = None

ServiceSpecificationAllOf.update_forward_refs()
