# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .target_service_schema import TargetServiceSchema


class ServiceSpecificationRefAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceSpecificationRefAllOf - a model defined in OpenAPI

        version: The version of this ServiceSpecificationRefAllOf [Optional].
        target_service_schema: The target_service_schema of this ServiceSpecificationRefAllOf [Optional].
    """

    version: Optional[str] = None
    target_service_schema: Optional[TargetServiceSchema] = None

ServiceSpecificationRefAllOf.update_forward_refs()
