# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .addressable import Addressable
from .attachment_ref import AttachmentRef
from .related_party_ref import RelatedPartyRef
from .service_level_specification_ref import ServiceLevelSpecificationRef
from .service_spec_characteristic import ServiceSpecCharacteristic
from .service_specification_all_of import ServiceSpecificationAllOf
from .service_specification_relationship import ServiceSpecificationRelationship
from .service_specification_state import ServiceSpecificationState
from .target_service_schema import TargetServiceSchema
from .time_period import TimePeriod


class ServiceSpecification(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceSpecification - a model defined in OpenAPI

        type: The type of this ServiceSpecification.
        base_type: The base_type of this ServiceSpecification [Optional].
        schema_location: The schema_location of this ServiceSpecification [Optional].
        id: The id of this ServiceSpecification.
        href: The href of this ServiceSpecification [Optional].
        name: The name of this ServiceSpecification [Optional].
        category: The category of this ServiceSpecification [Optional].
        subcategory: The subcategory of this ServiceSpecification [Optional].
        version: The version of this ServiceSpecification [Optional].
        description: The description of this ServiceSpecification [Optional].
        is_bundle: The is_bundle of this ServiceSpecification [Optional].
        last_update: The last_update of this ServiceSpecification [Optional].
        valid_for: The valid_for of this ServiceSpecification [Optional].
        lifecycle_status: The lifecycle_status of this ServiceSpecification [Optional].
        attachment: The attachment of this ServiceSpecification [Optional].
        related_party: The related_party of this ServiceSpecification [Optional].
        service_level_specification: The service_level_specification of this ServiceSpecification [Optional].
        service_spec_relationship: The service_spec_relationship of this ServiceSpecification [Optional].
        service_spec_characteristic: The service_spec_characteristic of this ServiceSpecification [Optional].
        target_service_schema: The target_service_schema of this ServiceSpecification [Optional].
    """

    type: str
    base_type: Optional[str] = None
    schema_location: Optional[AnyUrl] = None
    id: str
    href: Optional[AnyUrl] = None
    name: Optional[str] = None
    category: Optional[str] = None
    subcategory: Optional[str] = None
    version: Optional[str] = None
    description: Optional[str] = None
    is_bundle: Optional[bool] = None
    last_update: Optional[datetime] = None
    valid_for: Optional[TimePeriod] = None
    lifecycle_status: Optional[ServiceSpecificationState] = None
    attachment: Optional[List[AttachmentRef]] = None
    related_party: Optional[List[RelatedPartyRef]] = None
    service_level_specification: Optional[List[ServiceLevelSpecificationRef]] = None
    service_spec_relationship: Optional[List[ServiceSpecificationRelationship]] = None
    service_spec_characteristic: Optional[List[ServiceSpecCharacteristic]] = None
    target_service_schema: Optional[TargetServiceSchema] = None

ServiceSpecification.update_forward_refs()
