# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .referenceable import Referenceable
from .service_specification_relationship_all_of import ServiceSpecificationRelationshipAllOf
from .service_specification_relationship_type import ServiceSpecificationRelationshipType
from .time_period import TimePeriod


class ServiceSpecificationRelationship(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceSpecificationRelationship - a model defined in OpenAPI

        type: The type of this ServiceSpecificationRelationship.
        base_type: The base_type of this ServiceSpecificationRelationship [Optional].
        schema_location: The schema_location of this ServiceSpecificationRelationship [Optional].
        id: The id of this ServiceSpecificationRelationship.
        href: The href of this ServiceSpecificationRelationship [Optional].
        name: The name of this ServiceSpecificationRelationship [Optional].
        referred_type: The referred_type of this ServiceSpecificationRelationship.
        relationship_type: The relationship_type of this ServiceSpecificationRelationship [Optional].
        role: The role of this ServiceSpecificationRelationship [Optional].
        valid_for: The valid_for of this ServiceSpecificationRelationship [Optional].
    """

    type: str
    base_type: Optional[str] = None
    schema_location: Optional[AnyUrl] = None
    id: str
    href: Optional[AnyUrl] = None
    name: Optional[str] = None
    referred_type: str
    relationship_type: Optional[ServiceSpecificationRelationshipType] = None
    role: Optional[str] = None
    valid_for: Optional[TimePeriod] = None

ServiceSpecificationRelationship.update_forward_refs()
