# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

from enum import Enum
import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class ActionType(str, Enum):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ActionType - a model defined in OpenAPI

    """
    ADD       = "add"
    MODIFY    = "modify"
    DELETE    = "delete"
    NO_CHANGE = "noChange"
