# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class AddressableAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AddressableAllOf - a model defined in OpenAPI

        id: The id of this AddressableAllOf [Optional].
        href: The href of this AddressableAllOf [Optional].
        name: The name of this AddressableAllOf [Optional].
    """

    id: Optional[str] = None
    href: Optional[AnyUrl] = None
    name: Optional[str] = None

AddressableAllOf.update_forward_refs()
