# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class Error(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Error - a model defined in OpenAPI

        code: The code of this Error.
        reason: The reason of this Error.
        message: The message of this Error [Optional].
        status: The status of this Error [Optional].
        reference_error: The reference_error of this Error [Optional].
    """

    code: int
    reason: str
    message: Optional[List[str]] = None
    status: Optional[List[str]] = None
    reference_error: Optional[List[str]] = None

Error.update_forward_refs()
