# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .event_subscription_all_of import EventSubscriptionAllOf
from .event_subscription_input import EventSubscriptionInput


class EventSubscription(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EventSubscription - a model defined in OpenAPI

        query: The query of this EventSubscription.
        callback: The callback of this EventSubscription.
        id: The id of this EventSubscription.
    """

    query: str
    callback: str
    id: str

EventSubscription.update_forward_refs()
