# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class NoteAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    NoteAllOf - a model defined in OpenAPI

        author: The author of this NoteAllOf [Optional].
        date: The date of this NoteAllOf [Optional].
        system: The system of this NoteAllOf [Optional].
        text: The text of this NoteAllOf [Optional].
    """

    author: Optional[str] = None
    date: Optional[datetime] = None
    system: Optional[str] = None
    text: Optional[str] = None

NoteAllOf.update_forward_refs()
