# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .addressable import Addressable
from .place_all_of import PlaceAllOf


class Place(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Place - a model defined in OpenAPI

        type: The type of this Place.
        base_type: The base_type of this Place [Optional].
        schema_location: The schema_location of this Place [Optional].
        id: The id of this Place.
        href: The href of this Place [Optional].
        name: The name of this Place [Optional].
        role: The role of this Place [Optional].
    """

    type: str
    base_type: Optional[str] = None
    schema_location: Optional[AnyUrl] = None
    id: str
    href: Optional[AnyUrl] = None
    name: Optional[str] = None
    role: Optional[str] = None

Place.update_forward_refs()
