# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .referenceable import Referenceable
from .related_party_ref_all_of import RelatedPartyRefAllOf


class RelatedPartyRef(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RelatedPartyRef - a model defined in OpenAPI

        type: The type of this RelatedPartyRef.
        base_type: The base_type of this RelatedPartyRef [Optional].
        schema_location: The schema_location of this RelatedPartyRef [Optional].
        id: The id of this RelatedPartyRef.
        href: The href of this RelatedPartyRef [Optional].
        name: The name of this RelatedPartyRef [Optional].
        referred_type: The referred_type of this RelatedPartyRef.
        role: The role of this RelatedPartyRef [Optional].
    """

    type: str
    base_type: Optional[str] = None
    schema_location: Optional[AnyUrl] = None
    id: str
    href: Optional[AnyUrl] = None
    name: Optional[str] = None
    referred_type: str
    role: Optional[str] = None

RelatedPartyRef.update_forward_refs()
