# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .referenceable import Referenceable
from .service_specification_ref_all_of import ServiceSpecificationRefAllOf
from .target_service_schema import TargetServiceSchema


class ServiceSpecificationRef(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceSpecificationRef - a model defined in OpenAPI

        type: The type of this ServiceSpecificationRef.
        base_type: The base_type of this ServiceSpecificationRef [Optional].
        schema_location: The schema_location of this ServiceSpecificationRef [Optional].
        id: The id of this ServiceSpecificationRef.
        href: The href of this ServiceSpecificationRef [Optional].
        name: The name of this ServiceSpecificationRef [Optional].
        referred_type: The referred_type of this ServiceSpecificationRef.
        version: The version of this ServiceSpecificationRef [Optional].
        target_service_schema: The target_service_schema of this ServiceSpecificationRef [Optional].
    """

    type: str
    base_type: Optional[str] = None
    schema_location: Optional[AnyUrl] = None
    id: str
    href: Optional[AnyUrl] = None
    name: Optional[str] = None
    referred_type: str
    version: Optional[str] = None
    target_service_schema: Optional[TargetServiceSchema] = None

ServiceSpecificationRef.update_forward_refs()
