# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .extensible import Extensible
from .mef_service_configuration import MefServiceConfiguration
from .note import Note
from .place import Place
from .related_party_ref import RelatedPartyRef
from .resource_ref import ResourceRef
from .service_create_all_of import ServiceCreateAllOf
from .service_ref import ServiceRef
from .service_relationship import ServiceRelationship
from .service_specification_ref import ServiceSpecificationRef
from .service_state_type import ServiceStateType


class ServiceCreate(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceCreate - a model defined in OpenAPI

        type: The type of this ServiceCreate.
        base_type: The base_type of this ServiceCreate [Optional].
        schema_location: The schema_location of this ServiceCreate [Optional].
        category: The category of this ServiceCreate [Optional].
        description: The description of this ServiceCreate [Optional].
        mef_service_configuration: The mef_service_configuration of this ServiceCreate [Optional].
        note: The note of this ServiceCreate [Optional].
        place: The place of this ServiceCreate [Optional].
        related_party: The related_party of this ServiceCreate [Optional].
        service_relationship: The service_relationship of this ServiceCreate [Optional].
        service_specification: The service_specification of this ServiceCreate [Optional].
        service_type: The service_type of this ServiceCreate [Optional].
        state: The state of this ServiceCreate [Optional].
        supporting_resource: The supporting_resource of this ServiceCreate [Optional].
        supporting_service: The supporting_service of this ServiceCreate [Optional].
    """

    type: str
    base_type: Optional[str] = None
    schema_location: Optional[AnyUrl] = None
    category: Optional[str] = None
    description: Optional[str] = None
    mef_service_configuration: Optional[MefServiceConfiguration] = None
    note: Optional[List[Note]] = None
    place: Optional[List[Place]] = None
    related_party: Optional[List[RelatedPartyRef]] = None
    service_relationship: Optional[List[ServiceRelationship]] = None
    service_specification: Optional[ServiceSpecificationRef] = None
    service_type: Optional[str] = None
    state: Optional[ServiceStateType] = None
    supporting_resource: Optional[List[ResourceRef]] = None
    supporting_service: Optional[List[ServiceRef]] = None

ServiceCreate.update_forward_refs()
