# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .note import Note
from .related_party_ref import RelatedPartyRef
from .service_order_all_of import ServiceOrderAllOf
from .service_order_create import ServiceOrderCreate
from .service_order_item import ServiceOrderItem
from .service_order_relationship import ServiceOrderRelationship
from .service_order_state_type import ServiceOrderStateType


class ServiceOrder(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceOrder - a model defined in OpenAPI

        type: The type of this ServiceOrder.
        base_type: The base_type of this ServiceOrder [Optional].
        schema_location: The schema_location of this ServiceOrder [Optional].
        id: The id of this ServiceOrder.
        href: The href of this ServiceOrder [Optional].
        name: The name of this ServiceOrder [Optional].
        external_id: The external_id of this ServiceOrder [Optional].
        description: The description of this ServiceOrder [Optional].
        category: The category of this ServiceOrder [Optional].
        note: The note of this ServiceOrder [Optional].
        notification_contact: The notification_contact of this ServiceOrder [Optional].
        priority: The priority of this ServiceOrder [Optional].
        requested_start_date: The requested_start_date of this ServiceOrder [Optional].
        requested_completion_date: The requested_completion_date of this ServiceOrder [Optional].
        related_party: The related_party of this ServiceOrder [Optional].
        order_item: The order_item of this ServiceOrder [Optional].
        order_relationship: The order_relationship of this ServiceOrder [Optional].
        state: The state of this ServiceOrder [Optional].
        order_date: The order_date of this ServiceOrder [Optional].
        start_date: The start_date of this ServiceOrder [Optional].
        expected_completion_date: The expected_completion_date of this ServiceOrder [Optional].
        completion_date: The completion_date of this ServiceOrder [Optional].
    """

    type: str
    base_type: Optional[str] = None
    schema_location: Optional[AnyUrl] = None
    id: str
    href: Optional[AnyUrl] = None
    name: Optional[str] = None
    external_id: Optional[str] = None
    description: Optional[str] = None
    category: Optional[str] = None
    note: Optional[List[Note]] = None
    notification_contact: Optional[str] = None
    priority: Optional[int] = None
    requested_start_date: Optional[datetime] = None
    requested_completion_date: Optional[datetime] = None
    related_party: Optional[List[RelatedPartyRef]] = None
    order_item: Optional[List[ServiceOrderItem]] = None
    order_relationship: Optional[List[ServiceOrderRelationship]] = None
    state: Optional[ServiceOrderStateType] = None
    order_date: Optional[datetime] = None
    start_date: Optional[datetime] = None
    expected_completion_date: Optional[datetime] = None
    completion_date: Optional[datetime] = None

ServiceOrder.update_forward_refs()
