# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

from enum import Enum
import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class ServiceSpecificationState(str, Enum):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceSpecificationState - a model defined in OpenAPI

    """
    IN_STUDY = "IN_STUDY"
    IN_DESIGN = "IN_DESIGN"
    IN_TEST = "IN_TEST"
    LAUNCHED = "LAUNCHED"
    ACTIVE = "ACTIVE"
    RETIRED = "RETIRED"
    OBSOLETE = "OBSOLETE"
    REJECTED = "REJECTED"
