# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .addressable import Addressable
from .service_spec_characteristic_value_all_of import ServiceSpecCharacteristicValueAllOf
from .time_period import TimePeriod


class ServiceSpecCharacteristicValue(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceSpecCharacteristicValue - a model defined in OpenAPI

        type: The type of this ServiceSpecCharacteristicValue.
        base_type: The base_type of this ServiceSpecCharacteristicValue [Optional].
        schema_location: The schema_location of this ServiceSpecCharacteristicValue [Optional].
        id: The id of this ServiceSpecCharacteristicValue.
        href: The href of this ServiceSpecCharacteristicValue [Optional].
        name: The name of this ServiceSpecCharacteristicValue [Optional].
        is_default: The is_default of this ServiceSpecCharacteristicValue [Optional].
        range_interval: The range_interval of this ServiceSpecCharacteristicValue [Optional].
        regex: The regex of this ServiceSpecCharacteristicValue [Optional].
        unit_of_measure: The unit_of_measure of this ServiceSpecCharacteristicValue [Optional].
        value_from: The value_from of this ServiceSpecCharacteristicValue [Optional].
        value_to: The value_to of this ServiceSpecCharacteristicValue [Optional].
        value_type: The value_type of this ServiceSpecCharacteristicValue [Optional].
        valid_for: The valid_for of this ServiceSpecCharacteristicValue [Optional].
        value: The value of this ServiceSpecCharacteristicValue [Optional].
    """

    type: str
    base_type: Optional[str] = None
    schema_location: Optional[AnyUrl] = None
    id: str
    href: Optional[AnyUrl] = None
    name: Optional[str] = None
    is_default: Optional[bool] = None
    range_interval: Optional[str] = None
    regex: Optional[str] = None
    unit_of_measure: Optional[str] = None
    value_from: Optional[int] = None
    value_to: Optional[int] = None
    value_type: Optional[str] = None
    valid_for: Optional[TimePeriod] = None
    value: Optional[Dict[str, Any]] = None

ServiceSpecCharacteristicValue.update_forward_refs()
