# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .action_type import ActionType
from .extensible import Extensible
from .service_create import ServiceCreate
from .service_order_item_all_of import ServiceOrderItemAllOf
from .service_order_item_relationship import ServiceOrderItemRelationship
from .service_order_state_type import ServiceOrderStateType


class ServiceOrderItem(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceOrderItem - a model defined in OpenAPI

        type: The type of this ServiceOrderItem.
        base_type: The base_type of this ServiceOrderItem [Optional].
        schema_location: The schema_location of this ServiceOrderItem [Optional].
        id: The id of this ServiceOrderItem.
        action: The action of this ServiceOrderItem [Optional].
        service: The service of this ServiceOrderItem.
        state: The state of this ServiceOrderItem [Optional].
        order_item_relationship: The order_item_relationship of this ServiceOrderItem [Optional].
    """

    type: str
    base_type: Optional[str] = None
    schema_location: Optional[AnyUrl] = None
    id: str
    action: Optional[ActionType] = None
    service: ServiceCreate
    state: Optional[ServiceOrderStateType] = None
    order_item_relationship: Optional[List[ServiceOrderItemRelationship]] = None

ServiceOrderItem.update_forward_refs()
