# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .service_spec_characteristic_value import ServiceSpecCharacteristicValue
from .service_specification_relationship import ServiceSpecificationRelationship
from .time_period import TimePeriod


class ServiceSpecCharacteristicAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceSpecCharacteristicAllOf - a model defined in OpenAPI

        value_schema_location: The value_schema_location of this ServiceSpecCharacteristicAllOf [Optional].
        value_type: The value_type of this ServiceSpecCharacteristicAllOf [Optional].
        description: The description of this ServiceSpecCharacteristicAllOf [Optional].
        extensible: The extensible of this ServiceSpecCharacteristicAllOf [Optional].
        is_unique: The is_unique of this ServiceSpecCharacteristicAllOf [Optional].
        max_cardinality: The max_cardinality of this ServiceSpecCharacteristicAllOf [Optional].
        min_cardinality: The min_cardinality of this ServiceSpecCharacteristicAllOf [Optional].
        regex: The regex of this ServiceSpecCharacteristicAllOf [Optional].
        valid_for: The valid_for of this ServiceSpecCharacteristicAllOf [Optional].
        service_spec_char_relationship: The service_spec_char_relationship of this ServiceSpecCharacteristicAllOf [Optional].
        service_spec_characteristic_value: The service_spec_characteristic_value of this ServiceSpecCharacteristicAllOf [Optional].
    """

    value_schema_location: Optional[str] = None
    value_type: Optional[str] = None
    description: Optional[str] = None
    extensible: Optional[bool] = None
    is_unique: Optional[bool] = None
    max_cardinality: Optional[int] = None
    min_cardinality: Optional[int] = None
    regex: Optional[str] = None
    valid_for: Optional[TimePeriod] = None
    service_spec_char_relationship: Optional[List[ServiceSpecificationRelationship]] = None
    service_spec_characteristic_value: Optional[List[ServiceSpecCharacteristicValue]] = None

ServiceSpecCharacteristicAllOf.update_forward_refs()
