# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .time_period import TimePeriod


class ServiceSpecCharacteristicValueAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceSpecCharacteristicValueAllOf - a model defined in OpenAPI

        is_default: The is_default of this ServiceSpecCharacteristicValueAllOf [Optional].
        range_interval: The range_interval of this ServiceSpecCharacteristicValueAllOf [Optional].
        regex: The regex of this ServiceSpecCharacteristicValueAllOf [Optional].
        unit_of_measure: The unit_of_measure of this ServiceSpecCharacteristicValueAllOf [Optional].
        value_from: The value_from of this ServiceSpecCharacteristicValueAllOf [Optional].
        value_to: The value_to of this ServiceSpecCharacteristicValueAllOf [Optional].
        value_type: The value_type of this ServiceSpecCharacteristicValueAllOf [Optional].
        valid_for: The valid_for of this ServiceSpecCharacteristicValueAllOf [Optional].
        value: The value of this ServiceSpecCharacteristicValueAllOf [Optional].
    """

    is_default: Optional[bool] = None
    range_interval: Optional[str] = None
    regex: Optional[str] = None
    unit_of_measure: Optional[str] = None
    value_from: Optional[int] = None
    value_to: Optional[int] = None
    value_type: Optional[str] = None
    valid_for: Optional[TimePeriod] = None
    value: Optional[Dict[str, Any]] = None

ServiceSpecCharacteristicValueAllOf.update_forward_refs()
