# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .extensible import Extensible


class TargetServiceSchema(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TargetServiceSchema - a model defined in OpenAPI

        type: The type of this TargetServiceSchema.
        base_type: The base_type of this TargetServiceSchema [Optional].
        schema_location: The schema_location of this TargetServiceSchema [Optional].
    """

    type: str
    base_type: Optional[str] = None
    schema_location: Optional[AnyUrl] = None

TargetServiceSchema.update_forward_refs()
